### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by belidzs** [bennoleslie/pexif#22]
I'm using Windows 10 with Python 3.5.1. 
1. Installed pexif 0.15 with pip 
1. Installation completed without problems
1. Started a console window
1. Executed `import pexif`
1. Received the following exception:

``` python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pexif
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Balazs\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pexif.py", line 125
    print each,
             ^
SyntaxError: Missing parentheses in call to 'print'
>>>
```

**Comment by socketpair** [comment]
Even if that will be fixed, pexif DOES NOT SUPPOR Python3 actually. For example, it uses `StringIO` instead of `BytesIO`. Seems it is abandoned project.

**Comment by bennoleslie** [comment]
Python 3 is not supported. Forks or pull requests welcome.

**Comment by marcelometal** [comment]
Hi, I'm working to fix it:
https://github.com/marcelometal/pexif/

**Comment by TheSandDoctor** [comment]
@marcelometal Using your fork I keep getting the following:
```
primary = ef.get_exif().get_primary()
AttributeError: 'NoneType' object has no attribute 'get_primary'
```

**Comment by marcelometal** [comment]
@TheSandDoctor hi!

`pexif`was  abandoned, so I've replaced it with `piexif` =P

https://pypi.org/project/piexif/
